export const movies = [
  {
    movie_aid: 1,
    movie_title: "Wednesday",
    movie_year: "2023",
    movie_duration: "1 Season",
    movie_genre: "horror",
    movie_category: "TV Shows",
    movie_rating: "PG-13",
    movie_summary:
      "Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability, thwart a killing spree, and solve the mystery that embroiled her parents.",
    movie_cast: "Jenna Ortega, Hunter Dohan, Emma Myers",
    movie_image: "wednesday.webp",
    movie_is_active: true,
  },
  {
    movie_aid: 2,
    movie_title: "Girl From Nowhere",
    movie_year: "2018",
    movie_duration: "2 Seasons",
    movie_genre: "horror",
    movie_category: "TV Shows",
    movie_rating: "16+",
    movie_summary:
      "A mysterious, clever girl named Nanno transfers to different schools, exposing the lies and misdeeds of the students and faculty at every turn.",
    movie_cast: "Kitty Chicha, Tris Ren, Naomi Amante",
    movie_image: "girlFromNowhere.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 3,
    movie_title: "Chilling Adventures of Sabrina",
    movie_year: "2018",
    movie_duration: "4 Seasons",
    movie_genre: "horror",
    movie_category: "TV Shows",
    movie_rating: "16+",
    movie_summary:
      "As her 16th birthday nears, Sabrina Spellman must reconcile her dual nature as a half-witch, half-mortal while fighting the evil forces that threaten her, her family, and the daylight world humans inhabit.",
    movie_cast: "Kiernan Shipka, Ross Lynch, Lucy Davis",
    movie_image: "sabrina.webp",
    movie_is_active: true,
  },
  {
    movie_aid: 4,
    movie_title: "The Purge: Election Year",
    movie_year: "2016",
    movie_duration: "1hr 48mins",
    movie_genre: "Action, Horror",
    movie_category: "Western Movie",
    movie_rating: "18+",
    movie_summary:
      "Former Police Sergeant Barnes becomes head of security for Senator Charlie Roan, a Presidential candidate targeted for death on Purge night due to her vow to eliminate the Purge.",
    movie_cast: "Frank Grillo, Elizabeth Mitchell, Mykelti Williamson",
    movie_image: "purge-elec.png",
    movie_is_active: true,
  },
  {
    movie_aid: 5,
    movie_title: "Fear Street: Part One - 1994",
    movie_year: "2021",
    movie_duration: "1hr 47mins",
    movie_genre: "Horror",
    movie_category: "Western Movie",
    movie_rating: "16+",
    movie_summary:
      "A circle of teenage friends accidentally encounter the ancient evil responsible for a series of brutal murders that have plagued their town for over 300 years. Welcome to Shadyside.",
    movie_cast: "R.L. Stine, Kyle Killen, Phil Graziadei",
    movie_image: "fear-street.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 6,
    movie_title: "Gossip Girl",
    movie_year: "2007",
    movie_duration: "6 Seasons",
    movie_genre: "horror",
    movie_category: "TV Shows",
    movie_rating: "14+",
    movie_summary:
      "Narrated by a mysterious yet vicious blogger, this show follows a set of wealthy teenagers through their day to day scandalous lives as Manhattans Elite, and also how they betray each other for each other's gain.",
    movie_cast: "R.L. Stine, Kyle Killen, Phil Graziadei ",
    movie_image: "gossipgirl.webp",
    movie_is_active: true,
  },
  {
    movie_aid: 7,
    movie_title: "How to Get Away with Murder",
    movie_year: "2014",
    movie_duration: "6 Seasons",
    movie_genre: "horror",
    movie_category: "TV Shows",
    movie_rating: "14+",
    movie_summary:
      "A group of ambitious law students and their brilliant criminal defense professor become involved in a twisted murder plot that promises to change the course of their lives..",
    movie_cast: "Viola Davis, Billy Brown, Jack Falahee ",
    movie_image: "getawayr.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 8,
    movie_title: "Money Heist",
    movie_year: "2017",
    movie_duration: "6 Seasons",
    movie_genre: "Action, Crime, Drama",
    movie_category: "TV Shows",
    movie_rating: "14+",
    movie_summary:
      "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    movie_cast: "Úrsula Corberó, Álvaro Morte, Itziar Ituño",
    movie_image: "moneyheist.jpg",
    movie_is_active: true,
  },
  {
    movie_aid: 9,
    movie_title: "To All the Boys I've Loved Before",
    movie_year: "2018",
    movie_duration: "1hr 39m",
    movie_genre: "Romantic Comedy, Teen Drama",
    movie_category: "Western Movie",
    movie_rating: "14+",
    movie_summary:
      "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    movie_cast: "Lana Condor, Noah Centineo, Janel Parrish",
    movie_image: "toalltheboys.png",
    movie_is_active: true,
  },
  {
    movie_aid: 10,
    movie_title: "After",
    movie_year: "2019",
    movie_duration: "1hr 45m",
    movie_genre: "Steamy Romance, Teen Drama",
    movie_category: "Western Movie",
    movie_rating: "14+",
    movie_summary:
      "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    movie_cast: "Josephine Langford, Hero Fiennes Tiffin, Khadijha Red Thunder",
    movie_image: "after.png",
    movie_is_active: true,
  },
];